language: android
android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
before_script:
  - chmod ug+x ./gradlew
  #- sed -i -e '/signingConfigs.debug/d' app/build.gradle
before_install:
        - yes | sdkmanager "platforms;android-28"

